ALTER TABLE "Activity"
ADD COLUMN "formattedAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "mapProvider" TEXT NOT NULL DEFAULT '',
ADD COLUMN "mapPlaceId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "customLocation" BOOLEAN NOT NULL DEFAULT false;

